account/urls.py
from django.conf.urls import url
from django.urls import path
from .views import registration_view, login_view, logout_view, account_view

urlpatterns = [

    # url(r'^$', index, name='index'),
    url(r'^registration-form$', registration_view, name='registration-view'),
    url(r'^login-view$', login_view, name='login-view'),
    url(r'^logout$', logout_view, name='logout'),
    url(r'^account$', account_view, name='account'),








]

animals/urls.py
from django.conf.urls import url
from django.urls import path
from .views import index, gallery, blog, contacts_us, view_single, view_all_posts, add_comment, delete_comment, add_personal_post, add_new_post, view_add_blog, delete_post, update_post_list, update_post_blog, view_single_blog, add_post, adding_post
urlpatterns = [

    url(r'^$', index, name='index'),
    url(r'^gallery$', gallery, name='gallery'),
    url(r'^blog$', blog, name='blog'),
    url(r'^blog-colllection$', view_all_posts,
        name='blog-colllection'),  # all_blog_for_admin
    url(r'^add-personal-post$', add_personal_post, name='add-personal-post'),
    url(r'^contact-us$', contacts_us, name='contact-us'),
    url(r'^view_single/(?P<post_id>\d+)$', view_single,
        name='view-single'),  # palitan ko to for single view
    url(r'^delete_comment/(?P<comment_id>\d+)$',
        delete_comment, name='delete-comment'),
    url(r'^add_comment$', add_comment, name='add-comment'),  # add_comment
    url(r'^adding_post$', adding_post, name='adding_post'),  # add_post
    url(r'^view-add-blog$', view_add_blog, name='view-add-blog'),  # view_post
    url(r'^delete_post/(?P<post_id>\d+)$',
        delete_post, name='delete_post'),  # delete
    url(r'^update_post_list/(?P<post_id>\d+)$', update_post_list,
        name='update_post_list'),  # update_post_view_single
    url(r'^update_post_blog$', update_post_blog,
        name='update_post_blog'),  # update_pos_single
    url(r'^view_single_blog/(?P<post_id>\d+)$', view_single_blog,
        name='view_single_blog'),  # update_status_view_single
    # url(r'^update_status$', update_status, name='update_status')#update_status_single
    url(r'^add_post$', add_post, name='add_post'),  # add_post from
    url(r'^add_new_post$', add_new_post, name='add_new_post'),  # add_ from blog




]

endangered_animals/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
# from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('animals.urls', 'animals'), namespace="animals")),
    url(r'^', include(('account.urls', 'account'), namespace="account")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

animals/models.py
from django.db import models


class Post(models.Model):

    PUBLISH = 0
    NOT_PUBLISH = 1

    STATUS = (
        (PUBLISH, "Publish"),
        (NOT_PUBLISH, "Not Publish"),
    )

    # post_id = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name="Title", max_length=200)
    content = models.TextField(
        max_length=2000, help_text="Enter you blog text here.")
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    status = models.IntegerField(
        verbose_name="Status", choices=STATUS, default=0)
    created_by = models.CharField(verbose_name="Created By", max_length=200)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    commented_by = models.CharField(verbose_name="Created By", max_length=200)
    comment = models.TextField(max_length=2000, help_text="Comments..")
    post = models.CharField(verbose_name="Post Ref", max_length=200)
    date_commented = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" % self.post

animals/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'created_by']

# class ImageUploadForm(forms.Form):
#     my_image = forms.ImageField()


# class AccountAuthenticationForm(forms.ModelForm):

animals/views.py
from django.shortcuts import render
from pprint import pprint
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post, Comment
from django.core.files.storage import FileSystemStorage
from .forms import PostForm

import os
import datetime

# Create your views here.


def index(request):
    template = 'index.html'
    return render(request, template)


def gallery(request):
    template = 'gallery.html'
    return render(request, template)


def blog(request):  # view_all_Blog by users
    posts = Post.objects.filter(status=0)
    template = 'blog.html'
    context = {
        'posts': posts,  # same always
    }
    # context['data'] = 'Test Input'
    return render(request, template, context)


def view_single(request, post_id):
    single_post = Post.objects.get(id=int(post_id))
    comments = Comment.objects.filter(post=int(post_id))

    context = {
        'single_post': single_post,  # same always
        'comments': comments,  # same always
    }
    template = 'single.html'
    return render(request, template, context)


def view_all_posts(request):  # view_all_Post->For all Blog view by Admin
    posts = Post.objects.all()
    template = 'blog-colllection.html'
    context = {
        'posts': posts,  # same always
    }
    return render(request, template, context)


def contacts_us(request):
    template = 'contact.html'
    return render(request, template)


def add_personal_post(request):
    template = 'add-new-blog.html'
    return render(request, template)


def view_add_blog(request):
    form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'add-new-blog.html', context)


def add_new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            m = Post()
            m.image = form.cleaned_data['image']
            m.content = form.cleaned_data['content']
            m.title = form.cleaned_data['title']
            m.created_by = form.cleaned_data['created_by']
            m.status = 0
            m.date_posted = True
            m.save()
    # make an else for validation
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def adding_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            m = Post()
            m.image = form.cleaned_data['image']
            m.content = form.cleaned_data['content']
            m.title = form.cleaned_data['title']
            m.created_by = form.cleaned_data['created_by']
            m.status = 0
            m.date_posted = True
            m.save()
    else:
        return HttpResponseRedirect(reverse_lazy('animals:blog-colllection'))
    return HttpResponseRedirect(reverse_lazy('animals:blog-colllection'))


def update_post_blog(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            mYid = request.POST['id']
            m = Post.objects.get(id=int(mYid))
            m.image = form.cleaned_data['image']
            m.content = form.cleaned_data['content']
            m.title = form.cleaned_data['title']
            m.created_by = form.cleaned_data['created_by']
            m.status = request.POST['status']
            # m.date_posted = True
            m.save()
    else:
        return HttpResponseRedirect(reverse_lazy('animals:blog-colllection'))
    return HttpResponseRedirect(reverse_lazy('animals:blog-colllection'))


def view_single_blog(request, post_id):
    template = "view-post.html"
    data = Post.objects.get(id=int(post_id))
    context = {
        'data': data
    }
    return render(request, template, context)


def add_post(request):
    form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'add-post.html', context)


def update_status(request):
    if request.method == 'POST':
        mYid = request.POST['id']
        stat = Post.objects.get(id=int(mYid))
        # stat.status = form.cleaned_data['status']
        stat.save()
    else:
        return HttpResponseRedirect(reverse_lazy('animals:blog-collections'))
    return HttpResponseRedirect(reverse_lazy('animals:blog-collections'))


def update_post_list(request, post_id):
    template = "update-post.html"
    post_info = Post.objects.get(id=int(post_id))
    context = {
        'post_info': post_info
    }
    return render(request, template, context)


def delete_post(request, post_id):
    # template = "blog-collection.html"
    post_info = Post.objects.get(id=int(post_id))
    post_info.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def add_comment(request):
    post = request.POST["post"]
    commented_by = request.POST["commented_by"]
    comment = request.POST["comment"]
    info_comment = Comment(
        post=post, commented_by=commented_by, comment=comment)
    info_comment.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def delete_comment(request, comment_id):
    template = "single.html"
    comment = Comment.objects.get(id=int(comment_id))
    comment.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

animals/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Philippine Endangered Animals - Blog - Single</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" content="Dog Home Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!-- //Meta tag Keywords -->

	<!-- Custom-Files -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Bootstrap-Core-CSS -->
	<link rel="stylesheet" href="{% static 'css/blog.css' %}" type="text/css" media="all" />
	<!-- Blog-CSS -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom-Files -->

	<!-- Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Nunito+Sans:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese"
	 rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
	 rel="stylesheet">
	<!-- //Web-Fonts -->
</head>

    <body>


    {% block content %}

    {% endblock %}

	{% include 'components/footer.html' %}
	<!-- move top icon -->
	<a href="#home" class="move-top text-center"></a>
	<!-- //move top icon -->

    </body>

</html>

animals/templates/blog-colllection.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	</head>
	<body>
     	{% if request.user.is_authenticated %}
  		<p class="m-auto">Hello, {{request.user.username}}</p>
  	   {% endif %}
		<h1>List of All Blog</h1> <br /><br />

		<div class="">
		<a href="{% url 'animals:add_post' %}" class="btn btn-success">Add Blog</a> <br /><br />
		<a href="{% url 'account:logout' %}" class="btn btn-danger">LOGOUT</a> <br /><br />

		<div class="container">

            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Created By</th>
                        <th>Status</th>
                        <th>Date Publish</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
	            {% for data in posts %}
                    <tr>
                        <td>{{ data.title }}</td>
                        <td>{{ data.created_by }}</td>
                        <td>
                        {% if data.status == 0 %}
                            <p>Publish</p>
                        {% elif data.status == 1 %}
                            <p>Not Publish</p>
                        {% endif %}
                        </td>
                        <td>
                            {{ data.date_posted}}
                        </td>
                        <td>
                            <a href="{% url 'animals:view_single_blog' data.id %}" class="btn btn-primary">View</a>
                        </td>
                        <td>
                            <a href="{% url 'animals:update_post_list' data.id %}" class="btn btn-primary">Update</a>
                        </td>
                        <td>
                            <a href="{% url 'animals:delete_post' data.id %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
		</div>
		</div>

        <!-- Button trigger modal -->

{% comment %} modal  {% endcomment %}
            <!-- Modal -->
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                  {{ post_info.title }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
                </div>
            </div>
            </div>
{% comment %} modal  {% endcomment %}

	</body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

animals/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Philippine Endangered Animals</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" content="Dog Home Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>

	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link href="{% static 'css/css_slider.css' %}" type="text/css" rel="stylesheet" media="all">
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

	<!--// Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Nunito+Sans:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese"
	 rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
	 rel="stylesheet">
	<!-- //Web-Fonts -->
</head>

<body>
	<!-- //main banner -->
	<div class="main-top" id="home">
		<!-- header -->
		<header>
			<div class="container-fluid">
				<div class="header d-md-flex justify-content-between align-items-center py-3 px-xl-5 px-lg-3 px-2">
					<!-- logo -->
					<div id="logo">
						<h1><a class="" href="{% url 'animals:index' %}" >Endangered Animals of the Philippines</a></h1>
					</div>
					<!-- //logo -->

					<!-- nav -->
					<div class="nav_w3ls">
						<nav>
							<label for="drop" class="toggle">Menu</label>
							<input type="checkbox" id="drop" />
							<ul class="menu">
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="{% url 'animals:index' %}" class="active">Home</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="{% url 'animals:gallery' %}">Gallery</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<!-- First Tier Drop Down -->
									<label for="drop-2" class="toggle toogle-2">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#">All Blog <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<input type="checkbox" id="drop-2" />
									<ul>

										<li><a href="{% url 'animals:blog' %}" class="drop-text">Blog</a></li>
										<li><a href="{% url 'animals:view-add-blog'%}" class="drop-text">Add Blog</a></li>
										<li><a href="#what" class="drop-text">What We do</a></li>
									</ul>
								</li>
								<li><a href="{% url 'animals:contact-us' %}">Contact Us</a></li>
							</ul>
						</nav>
					</div>
					<!-- //nav -->
				</div>
			</div>
		</header>
		<!-- //header -->

		<!-- banner -->
		<div class="banner_w3lspvt">
			<div class="csslider infinity" id="slider1">
				<input type="radio" name="slides" checked="checked" id="slides_1" />
				<input type="radio" name="slides" id="slides_2" />
				<input type="radio" name="slides" id="slides_3" />
				<input type="radio" name="slides" id="slides_4" />
				<ul class="banner_slide_bg">
					<li>
						<div class="container">
							<div class="w3ls_banner_txt text-center ml-auto pr-xl-0 pr-sm-4 pr-5">
								<h3 class="w3ls_pvt-title text-wh text-uppercase let mb-2">The Philippine Eagle</h3>
								<p> Also know as the Monkey Eating Eagle or the Great Philippine Eagle, the Philippine Eagle
									 is considered one of the largest of the extant eagles in the world
									  in terms of length and wing surface. Among the rarest and most
										powerful birds in the world, it has been declared the Philippines'
										bational bird. It is critically endangered, mainly due to
										massive loss of habitat resulting from deforestation in most
										of its range. Killing a Philippine eagle is punishable under
										Philippine law by up to 12 years in prison and heavy fines.</p>

							</div>
						</div>
					</li>
					<li>
						<div class="container">
							<div class="w3ls_banner_txt text-center ml-auto pr-xl-0 pr-sm-4 pr-5">
								<h3 class="w3ls_pvt-title text-wh text-uppercase let mb-2"> The Tamaraw </h3>
								<p>The Tamaraw is a small hoofed mammal that contrary to common belief and
								past classification, is not a subspecies of the local carabao,
								 which is only slightly larger, or the common water buffalo. In contrast
								 to the carabao, it has a number of distinguishing characteristics: it is
								 slightly hairier, has light markings on its face, is not gregarious, and
								 has shorter horns that are V-shaped. It is the second largest
									native terrestrial mammal in the country next only to the carabao.
									It is endemic to the island of Mindoro and is the only endemic Philippine
									bovine. The tamaraw was originally found all over Mindoro, from
									sea level up to the mountains (2000 meters above sea level),
									but because of human habitation, hunting, and logging/deforestation, it is
									now restricted to only a few remote grassy plains and is now
									a critically endangered species. </p>

							</div>
						</div>
					</li>
					<li>
						<div class="container">
							<div class="w3ls_banner_txt text-center ml-auto pr-xl-0 pr-sm-4 pr-5">
								<h3 class="w3ls_pvt-title text-wh text-uppercase let mb-2">The Philippine Naked-Backed Fruit Bat</h3>
								<p> The Philippine naked-backed fruit bat is known to be the
									largest cave-dwelling bats in the country and is only native
									to Cebu and Negros. As early as 1970, this rare species of
									megabat has already been “presumed extinct” due to hunting and
									habitat destruction. In 2008, IUCN officially listed the Philippine
									naked-backed fruit as critically endangered. The population count is unknown
								but only 2 small populations live in Cebu. </p>

							</div>
						</div>
					</li>
					<li>
						<div class="container">
							<div class="w3ls_banner_txt text-center ml-auto pr-xl-0 pr-sm-4 pr-5">
								<h3 class="w3ls_pvt-title text-wh text-uppercase let mb-2"> The Philippine Crocodile</h3>
								<p>Also known as the Mindoro crocodile, the Philippine Crocodile
									used to be common throughout the country but because of habitat
									loss, dynamite fishing and hunting by humans, these freshwater
									crocodiles can now only be found on the islands of Dalupiri, Luzon,
									 and Mindanao. Currently, their population size is at 92-137.</p>

							</div>
						</div>
					</li>
				</ul>
				<div class="arrows">
					<label for="slides_1"></label>
					<label for="slides_2"></label>
					<label for="slides_3"></label>
					<label for="slides_4"></label>
				</div>
				<div class="navigation">
					<div>
						<label for="slides_1"></label>
						<label for="slides_2"></label>
						<label for="slides_3"></label>
						<label for="slides_4"></label>
					</div>
				</div>
			</div>
		</div>
		<!-- //banner -->
	</div>
	<!-- //main banner -->

	<!-- about -->
	<div class="what py-5">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-sm-4 mb-3 text-bl text-center font-weight-bold">THE PHILIPPINES</h3>
			<p class="mx-auto wstyles text-center mb-sm-5 mb-4"> The Philippines is
				one of the 17 megadiverse countries in the world which hosts a diverse
				array of plant and animal species.
				The Department of Environment and Natural Resources (DENR) reported
				that the Philippines is home to more than 52,177 endemic species. Although the Philippines has
				a “high degree of land and animal endemism,” it is also tagged as a
				biodiversity hotspot as the number of endangered and threatened species
				 continues to grow due to habitat loss, pollution, illegal mining, deforestation and inhumane animal activities.
				<br> <br> Source: <a href="https://pop.inquirer.net/74580/time-is-running-out-for-these-critically-endangered-species-in-the-philippines#ixzz6EDvzPdrn">https://pop.inquirer.net/74580/time-is-running-out-for-these-critically-endangered-species-in-the-philippines#ixzz6EDvzPdrn</a>
</p>
			<img src="{% static 'images/eagle2.jpg' %}" alt="" class="img-fluid">
		</div>
	</div>
	<!-- //about -->


<!-- what we do -->
	<div class="what pb-5" id="what">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 text-bl text-center font-weight-bold mb-sm-5 mb-4">What we do</h3>

			<h2 class="title-w3 text-bl text-center font-weight-bold mb-sm-5 mb-4"> RAISE AWARENESS </h2>
			<p>
			IRaise Awareness is a worldwide effort that not only educates about our most endangered species, but also teaches how to rescue them!

We've got activities to help you and your children raise awareness about endangered species to make the planet a better place.

The activities can be tailored to support endangered species in general or a specific type of animal. It’s up to you how you customize them.

Get more ideas with our IRaise Awareness toolkit.
			</p>

		</div>
	</div>
	<!-- //what we do -->
	<!-- stats section -->
	<div class="stats py-5" id="stats">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 text-wh text-center font-weight-bold mb-sm-5 mb-4"> Statistics in 2019</h3>
			<div class="row text-center py-sm-3">
				<div class="col-md-3 col-sm-6 w3layouts_stats_left">
					<p class="counter">800</p>
					<p class="para-text-w3ls text-li">The Philippine Eagle</p>
				</div>
				<div class="col-md-3 col-sm-6 w3layouts_stats_left mt-md-0 mt-4">
					<p class="counter">480</p>
					<p class="para-text-w3ls text-li">The Tamaraw</p>
				</div>
				<div class="col-md-3 col-sm-6 w3layouts_stats_left mt-md-0 mt-4">
					<p class="counter" > 5,000 to 10,000</p>
					<p class="para-text-w3ls text-li">The Tarsier </p>
				</div>
				<div class="col-md-3 col-sm-6 w3layouts_stats_left mt-md-0 mt-4">
					<p class="counter">137</p>
					<p class="para-text-w3ls text-li">The Philippine Crocodile</p>
				</div>
			</div>
		</div>
	</div>
	<!-- //stats section -->

	{% include 'components/footer.html' %}

	<!-- move top icon -->
	<a href="#home" class="move-top text-center"></a>
	<!-- //move top icon -->


</body>

</html>

animals/templates/single.html
{% extends 'base.html' %}

{% block content %}
	{% include 'components/maintop-header.html' %}
	<!-- //main banner -->

	<!-- single -->
	<div class="blog-w3l py-5">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 text-bl text-center font-weight-bold mb-sm-5 mb-4">Blog Details</h3>
			<div class="row blog-content pt-lg-3">

				<div class="col-lg-12 blog_section">
					<div class="card border-0">
						<a href="">
							<img class="card-img-top" src="{{ single_post.image.url }}" alt="">
						</a>
						<div class="card-body">
							<div class="row border-bottom pb-3">
								<div class="col-sm-6 col-4 perso-wthree">
									<h6 class="blog-first text-bl">
										<span class="fa fa-user mr-2"></span>{{ single_post.created_by }}
									</h6>
								</div>
								<div class="col-sm-6 col-8 info-commt text-right">
									<ul class="blog_list">
										<li>{{ single_post.date_posted }}</li>
									</ul>
								</div>
							</div>
							<a href="" class="text-bl font-weight-bold blog-grid-title mt-4 mb-3">{{ single_post.title }}</a>
							<p class="card-text">{{ single_post.content }}</p>
						</div>
					</div>
					<div class="comment-top mt-5">
						<h4>Comments</h4>
						{% for comment in comments%}
							<div class="media">
									<div class="media-body pt-xl-2 pl-3">
										<p>
											<h5>{{ comment.commented_by }} - {{ comment.date_commented }}  <a href="{% url 'animals:delete-comment' comment.id %}">x</a></h5>
										</p>
										<p>
										{{ comment.comment }}
										</p>
									</div>
							</div>
						{% endfor %}

					</div>
					<div class="comment-top mt-5">
						<h4>Leave a Comment</h4>
						<div class="comment-bottom agileinfo_mail_grid_right">
							<form action="{% url 'animals:add-comment' %}" method="POST">
								{% csrf_token %}
								<div class="form-group">
									<input name="post" type="hidden" value="{{ single_post.id }}">
									<input class="form-control" type="text" name="commented_by" placeholder="Name" required="">
								</div>
								<div class="form-group">
									<textarea class="form-control" name="comment" placeholder="Message..." required=""></textarea>
								</div>
								<button type="submit" class="btn btn-primary submit">Submit</button>
							</form>
						</div>
					</div>
				</div>


				<!-- //right side -->
			</div>
		</div>
	</div>
{% endblock %}